steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mars-rover-pics-263717/mars-rover-pics:${SHORT_SHA}', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mars-rover-pics-263717/mars-rover-pics']
    # deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'mars-rover-pics', '--image', '--platform', 'gcr.io/mars-rover-pics-263717/mars-rover-pics:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']
    env:
    - 'PORT=8081'
images:
  - gcr.io/mars-rover-pics-263717/mars-rover-pics